In [7]:
!pip install gym
!pip install --upgrade IPython

Requirement already up-to-date: IPython in c:\users\hp\anaconda3\lib\site-packages (7.20.0)


In [34]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [35]:
env = gym.make("FrozenLake-v0")

In [36]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [38]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state,reward,done,info = env.step(action)
        
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done==True:
            break
            
    exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
        
print("********Average reward per thousand episode********")
for r in rewards_per_thousand_episodes:
    print(count," : ",str(sum(r/1000)))
    count+=1000
            
            
print("\n\n*********Q-table*********\n")
print(q_table)

********Average reward per thousand episode********
1000  :  0.036000000000000025
2000  :  0.20000000000000015
3000  :  0.3950000000000003
4000  :  0.5670000000000004
5000  :  0.6410000000000005
6000  :  0.6450000000000005
7000  :  0.6850000000000005
8000  :  0.6940000000000005
9000  :  0.7040000000000005
10000  :  0.7020000000000005


*********Q-table*********

[[0.6076213  0.51231843 0.51202121 0.48793721]
 [0.33185232 0.42538079 0.41712397 0.5316721 ]
 [0.4133217  0.42262896 0.39568095 0.48116752]
 [0.31220134 0.28759948 0.37353883 0.45867457]
 [0.64120452 0.46227892 0.45152492 0.31043615]
 [0.         0.         0.         0.        ]
 [0.16845646 0.07613408 0.42073174 0.14372733]
 [0.         0.         0.         0.        ]
 [0.51965018 0.33578964 0.38617195 0.66758012]
 [0.483927   0.72866177 0.42716561 0.33874137]
 [0.69879936 0.49846298 0.38065211 0.2396304 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.56022777 0.45309569 

In [42]:
for episode in range(3):
    state = env.reset()
    done = False
    print("***********Episode",episode+1,"*************\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state,reward,done,info = env.step(action)
        
        if done==True:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("*****Your reached the Goal!*****")
                time.sleep(3)
            else:
                print("*****You fell through a holl!*****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
*****Your reached the Goal!*****
